# System-wide packages (environment.systemPackages).
# Find packages at https://search.nixos.org/.
{ config, lib, pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    vim
    wget
    pciutils
    btop
    neovim
    pavucontrol
    libnotify
    xwallpaper
    nautilus
    file-roller
    vivaldi
    gedit
    mpv
    flatpak
    lutris
    discord
    rofi
    nitrogen
    parted
    bat
    spotify
    eza
    mesa
    tldr
    fastfetch
    git
    htop
    nvtopPackages.amd
    samba
    scrot
    clock-rs
    xcp
    nyaa
    rtorrent
    transmission_4
    gcc
    image-roll
    imv
    pcmanfm
    fishPlugins.done
    fishPlugins.fzf-fish
    fishPlugins.forgit
    fishPlugins.hydro
    fzf
    fishPlugins.grc
    grc
    alacritty
    swaybg
    xwayland-satellite
    waypaper
    psmisc
    quodlibet
    cava
    grim
    polychromatic
    input-remapper
    python3
    python3Packages.pip
    python3Packages.flask
    python3Packages.rich
    jamesdsp
    claude-code
    cargo
    rustc
    rustfmt
    rust-analyzer
    android-tools
    nodejs
    nix-tree
    darktable
    filezilla
    protonup-qt
  ];
}
